# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e64dd4769bcaafa247e12f1ad84882de62711f43085e612f291ba8c33f4d3e53b3e67dd99b9ad1c0aacb6c65fd0a3f9337bd046a72483c82d1c12a1962ec805b

test:
  secret_key_base: b9b06aa835536c4ad636c74ff899b9a512680a09717ad92d3c9480699d84afaad81bbd28e85281d64035e6aa5e422b684b28676a3541c5d9b412f35719ffe4de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
